apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: flasknode
  ports:
  - name: flask-app
    protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30006
  type: NodePort
